[package]
name = "aoc_util"
version = "0.0.0"
authors = ["Rasmus Rosengren <rasmus.rosengren@protonmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.5"
dotenv = "0.15"
reqwest = { version = "0.11", features = ["blocking"] }
