[package]
name = "aoc_macro"
version = "0.0.0"
authors = ["Rasmus Rosengren <rasmus.rosengren@protonmail.com>"]
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
